// Package docs Code generated by swaggo/swag.
// This file was automatically generated and should not be edited.
package docs

// This is a placeholder file for Swagger documentation
// The actual documentation will be generated by swag init command
